spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616 # 目标地址，61616 端口为 JMS 协议，具体查看在 apache-activemq-5.16.1/conf/activemq.xml
    user: admin
    password: admin
    pool:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/java_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
